server {
    listen 80;

    server_name localhost;

    location /projeto-korp {
        proxy_pass http://http-server-korp:8080/projeto-korp;
    }

    location /health {
        proxy_pass http://http-server-korp:8080/health;
    }
}
